apiVersion: v1
kind: Service
metadata:
  name: flowcar-service
  namespace: webapp
spec:
  selector:
    app: flowcar
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
