name: Deployment

on:
  push:
    tags:
      - "**"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: webapp
          push: true
          tags: fraguinha/flowcar-webapp:latest
          cache-from: type=registry,ref=fraguinha/flowcar-webapp:buildcache
          cache-to: type=registry,ref=fraguinha/flowcar-webapp:buildcache,mode=max
          platforms: linux/amd64,linux/arm64/v8

  ssh:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
          cat >> ~/.ssh/config << EOF
          Host production
            HostName $SSH_HOST
            User $SSH_USERNAME
            IdentityFile ~/.ssh/private.key
            StrictHostKeyChecking no
          EOF

      - name: Rollout deployment
        run: ssh production 'kubectl rollout restart deployment flowcar-deployment'
