name: Platform

on:
  push:
    branches:
      - "main"
    paths:
      - "k8s/**"
  workflow_dispatch:

jobs:
  kubernetes:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
          cat >> ~/.ssh/config << EOF
          Host production
            HostName $SSH_HOST
            User $SSH_USERNAME
            IdentityFile ~/.ssh/private.key
            StrictHostKeyChecking no
          EOF

      - name: Apply manifests
        run: ssh production 'cd /opt/flowcar && git fetch --all && git pull --rebase --autostash origin main && kubectl apply -k k8s/overlays/production'
